version: "3.4"
services:
  api:
    # image: ft_transcendence
    build:
      dockerfile: Dockerfile-back
      context: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - '3000:3000'
    restart: always
    # networks:
    #   - db
    #   - app
  app:
    build:
      context: .
      dockerfile: Dockerfile-front
    # volumes:
    #   - '.:/app'
    #   - '/app/node_modules'
    ports:
      - '3001:8080'
    restart: always
    # volumes:
    #   - type: bind
    #     source: ./front
    #     target: /usr/src/app-front

  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password