FROM node:17

# Create app directory, in our container/image
WORKDIR /usr/src/app-back

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY ./back/package*.json ./
RUN npm install --location=global npm@8.5.5
RUN npm install
# RUN npm audit fix --force
# If you are building your code for production

# Bundle app source
COPY ./back/ .

RUN npm run build

# ENV NODE_ENV production
# RUN npm ci --only=production && npm cache clean --force

# USER node


EXPOSE 3000

CMD [ "npm", "run", "start:prod" ]
# CMD [ "node", "dist/main.js" ]