FROM node:16

WORKDIR /usr/src/app-front

COPY front/package*.json ./

RUN npm install @vue/cli-service
# RUN npm install --location=global @vue/cli
RUN npm install --location=global npm@8.5.5
RUN npm install
# RUN npm audit fix --force


COPY front/ .

RUN npm run build

ENV PORT=8080
EXPOSE 8080

CMD ["serve", "-s", "./dist/"]
