FROM node:16

WORKDIR /usr/src/app-front

COPY front/package*.json ./

RUN npm install @vue/cli-service
# RUN npm install --location=global @vue/cli
RUN npm install --location=global npm@8.5.5
RUN npm install


COPY front/ .

EXPOSE 8080 3001

CMD ["npm", "run", "serve"]