FROM node:16

WORKDIR /usr/src/app-front

COPY front/package*.json ./

RUN npm install -g npm@8.5.5
RUN npm install
RUN npm install -g @vue/cli 
RUN npm install @vue/cli-service


COPY front/ .

EXPOSE 8080

CMD ["npm", "run", "serve"]